<?php

return [
    ['name' => 'Reservas e calendário', 'icon' => 'calendar-event', 'allowed_roles' => ['16']],
    ['name' => 'Documentação de Crisma', 'icon' => 'file-earmark-text', 'url' => '/docs-crisma', 'allowed_roles' => ['3', '13']],
    ['name' => 'Documentação de Eucaristia', 'icon' => 'file-earmark-text', 'url' => '/docs-eucaristia', 'allowed_roles' => ['7', '12']],
    ['name' => 'Estoque', 'icon' => 'box-seam', 'allowed_roles' => ['15', '4']],
    ['name' => 'Inventário', 'icon' => 'clipboard-data', 'allowed_roles' => ['15']],
    ['name' => 'Buckets de mídia', 'icon' => 'collection-play', 'allowed_roles' => ['*']],
    ['name' => 'Acessos de usuários', 'icon' => 'people', 'allowed_roles' => []], // Only Admins
    ['name' => 'Configurações', 'icon' => 'gear', 'url' => '/settings', 'allowed_roles' => []], // Only Admins
    ['name' => 'Escalas de Acólitos e Coroinhas', 'icon' => 'calendar-check', 'url' => '/acolitos/escalas', 'allowed_roles' => ['6', '8']],
    ['name' => 'Funções de Acólitos e Coroinhas', 'icon' => 'list-task', 'url' => '/acolitos/funcoes', 'allowed_roles' => ['6', '8']],
    ['name' => 'Notas e Avisos de Acólitos e Coroinhas', 'icon' => 'journal-bookmark', 'url' => '/acolitos/notes', 'allowed_roles' => ['6', '8']],
    ['name' => 'Lista de Acólitos e Coroinhas', 'icon' => 'person-lines-fill', 'url' => '/acolitos', 'allowed_roles' => ['6']],
    ['name' => 'Vicentinos', 'icon' => 'heart', 'allowed_roles' => ['4']],
    ['name' => 'Primeira eucaristia', 'icon' => 'cup-straw', 'allowed_roles' => ['7', '12']],
    ['name' => 'Comunidades', 'icon' => 'houses', 'url' => '/comunidades', 'allowed_roles' => ['15']],
    ['name' => 'Salas e espaços', 'icon' => 'door-open', 'url' => '/reservas-locais', 'allowed_roles' => ['15']],
    ['name' => 'Lembretes', 'icon' => 'bell', 'url' => '/lembretes', 'allowed_roles' => ['*']],
    ['name' => 'Pascom', 'icon' => 'camera', 'allowed_roles' => ['9', '10']],
    ['name' => 'Inscrições crisma', 'icon' => 'pencil-square', 'allowed_roles' => ['3']],
    ['name' => 'Inscrições eucaristia', 'icon' => 'pencil-square', 'allowed_roles' => ['7']],
    ['name' => 'Inscrições de catequese de adultos', 'icon' => 'pencil-square', 'allowed_roles' => ['17']],
    ['name' => 'Solicitações de segunda via', 'icon' => 'file-earmark-plus', 'allowed_roles' => []],
    ['name' => 'Avisos paroquiais', 'icon' => 'megaphone', 'allowed_roles' => []],
    ['name' => 'Comunicação em massa', 'icon' => 'broadcast', 'allowed_roles' => []],
    ['name' => 'Chat', 'icon' => 'chat-dots', 'url' => '/chat', 'allowed_roles' => ['3', '7', '17', '12', '13', '6', '8', '9', '10', '4', '16']],
    ['name' => 'Excursões', 'icon' => 'bus-front', 'url' => '/excursoes', 'allowed_roles' => []],
    ['name' => 'Registros gerais', 'icon' => 'journal-text', 'url' => '/registers', 'allowed_roles' => ['3', '7', '6', '9', '4']],
    ['name' => 'Protocolos', 'icon' => 'shield-check', 'allowed_roles' => ['*']],
    ['name' => 'Catequistas de Primeira Eucaristia', 'icon' => 'person-badge', 'url' => '/catequistas-eucaristia', 'allowed_roles' => ['7', '12']],
    ['name' => 'Catequistas de Crisma', 'icon' => 'person-badge-fill', 'url' => '/catequistas-crisma', 'allowed_roles' => ['3', '13']],
    ['name' => 'Catequistas de Catequese de Adultos', 'icon' => 'person-badge-fill', 'url' => '/catequistas-adultos', 'allowed_roles' => ['17']],
    ['name' => 'Turmas de Primeira Eucaristia', 'icon' => 'people-fill', 'url' => '/turmas-eucaristia', 'allowed_roles' => ['7', '12']],
    ['name' => 'Turmas de Crisma', 'icon' => 'people', 'url' => '/turmas-crisma', 'allowed_roles' => ['3', '13']],
    ['name' => 'Turmas de Catequese de Adultos', 'icon' => 'people', 'url' => '/turmas-adultos', 'allowed_roles' => ['17']],
    ['name' => 'Notas Fiscais', 'icon' => 'receipt', 'url' => '/notas-fiscais', 'allowed_roles' => ['11', '14', '2']],
    ['name' => 'Ofertas e Dízimos', 'icon' => 'cash-coin', 'url' => '/ofertas', 'allowed_roles' => ['11', '14']],
    ['name' => 'Início', 'icon' => 'house', 'allowed_roles' => ['*']], // Everyone
];
