<?php

return [
    ['name' => 'Reservas e calendário', 'icon' => 'calendar-event'],
    ['name' => 'Documentação para crisma a primeira eucaristia', 'icon' => 'file-earmark-text'],
    ['name' => 'Estoque', 'icon' => 'box-seam'],
    ['name' => 'Inventário', 'icon' => 'clipboard-data'],
    ['name' => 'Buckets de mídia', 'icon' => 'collection-play'],
    ['name' => 'Acessos de usuários', 'icon' => 'people'],
    ['name' => 'Configurações', 'icon' => 'gear', 'url' => '/settings'],
    ['name' => 'Acólitos e coroinhas', 'icon' => 'person-badge'],
    ['name' => 'Vicentinos', 'icon' => 'heart'],
    ['name' => 'Primeira eucaristia', 'icon' => 'cup-straw'],
    ['name' => 'Catequese de adultos', 'icon' => 'book'],
    ['name' => 'Comunidades', 'icon' => 'houses'],
    ['name' => 'Salas e espaços', 'icon' => 'door-open'],
    ['name' => 'Lembretes', 'icon' => 'bell', 'url' => '/lembretes'],
    ['name' => 'Pascom', 'icon' => 'camera'],
    ['name' => 'Inscrições crisma', 'icon' => 'pencil-square'],
    ['name' => 'Inscrições eucaristia', 'icon' => 'pencil-square'],
    ['name' => 'Inscrições de catequese de adultos', 'icon' => 'pencil-square'],
    ['name' => 'Solicitações de segunda via', 'icon' => 'file-earmark-plus'],
    ['name' => 'Avisos paroquiais', 'icon' => 'megaphone'],
    ['name' => 'Comunicação em massa', 'icon' => 'broadcast'],
    ['name' => 'Chat', 'icon' => 'chat-dots', 'url' => '/chat'],
    ['name' => 'Excursões', 'icon' => 'bus-front'],
    ['name' => 'Registros gerais', 'icon' => 'journal-text', 'url' => '/registers'],
    ['name' => 'Protocolos', 'icon' => 'shield-check'],
    ['name' => 'Catequese de Primeira Eucaristia', 'icon' => 'book', 'url' => '/catequese-eucaristia'],
    ['name' => 'Catequese de Crisma', 'icon' => 'fire', 'url' => '/catequese-crisma'],
    ['name' => 'Catequistas de Primeira Eucaristia', 'icon' => 'person-badge', 'url' => '/catequistas-eucaristia'],
    ['name' => 'Catequistas de Crisma', 'icon' => 'person-badge-fill', 'url' => '/catequistas-crisma'],
    ['name' => 'Início', 'icon' => 'house'],
];
